version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6
    restart: "always"
    environment:
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
    ports:
      - "15672:15672"
      - "5672:5672"