version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6
    restart: "always"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
    ports:
      - ${RABBIT_MQ_DEFAULT_PORT}:5672
      - ${RABBIT_MQ_HTTP_PORT}:15672
