version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6
    restart: "always"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"